In [1]:
import numpy as np

In [21]:
x = [21, 23, 27, 32, 34, 41, 50, 53, 57, 59, 38, 46, 48, 48, 60]
y = [1000, 1100, 1250, 1700, 1500, 1980,
     2500, 3500, 2200, 4100, 3900, 5100, 5500, 7000, 6500]

TypeError: ignored

In [7]:
import plotly.express as px

In [8]:
grafico = px.scatter(x = x, y = y)
grafico.show()

In [35]:
i = 0
while  i <= 14:
  base_salario = np.append(x[i], y[i])
  base_salario = base_salario.reshape(1, 2)
  print(base_salario)
  i += 1

[[  21 1000]]
[[  23 1100]]
[[  27 1250]]
[[  32 1700]]
[[  34 1500]]
[[  41 1980]]
[[  50 2500]]
[[  53 3500]]
[[  57 2200]]
[[  59 4100]]
[[  38 3900]]
[[  46 5100]]
[[  48 5500]]
[[  48 7000]]
[[  60 6500]]


In [27]:
# biblioteca de normalizacao de dados
from sklearn.preprocessing import StandardScaler

In [36]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)
print(base_salario)

[[0. 0.]]


In [ ]:
from sklearn.cluster import KMeans
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

In [ ]:
centroide = kmeans_salario.cluster_centers_
centroide

In [ ]:
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)

In [ ]:
rotulos = kmeans_salario.labels_
rotulos

In [ ]:
import plotly.graph_objects as go
grafico1 = px.scatter(x = base_salario[:, 0], y = base_salario[:, 1], color = rotulos)
grafico2 = px.scatter(x = centroide[:0], y = centroide[:, 1], size = [8, 8, 8])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico1.show()