Numpy arrays são numeros, onde seus indices que variam de 0 a n-1. 

In [2]:
import numpy as np


In [ ]:
num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
num[1] # acessa o segundo item da lista
num[-1] # acessa o ultimo item da lista

Em arrays 2D(matriz), sera acessado por dois leveis - LINHA e COLUNA


In [ ]:
b[i, j] # i = linha, j = coluna do array

Slicing retorna o fateamento de um array, sempre indicando o inicio e o fina do fatiamento

In [ ]:
num[1:4] # ira retonar os valores entre 1 e 4, excluindo o ultimo
b[1:3, 1:4] # em nivel 2D, sera a mesma coisa

In [ ]:
x = np.linspace(start=10, stop=100, num=10) # cra um array com tamanho e intercalacao definida
print('x:', x)
print('shape: ', x.shape) # retorna o tamanho do array

Extracao de elementos em Arrays

In [ ]:
print(x[0])
print(x[1])
print(x[4])
print(x[-1])
print(x[-3]) #do final para o inicio

In [ ]:
print(x[0:3]) # 3 primeiros elementos
print(x[:3]) # 3 primeiros elementos tbm
print(x[-2:]) # 2 ultimos primeiros numeros

In [ ]:
x = x.reshape(2, 5) # redimensiona o array para L e C (matriz) de acordo com seu tamanho
print(x)
print(x[0, 1])
print(x[1, -2])
print(x[1, 4])

In [15]:
print(x[0:1, 1:3]) # slicing em arrays com duas dimensoes
print(x[0, 1:]) # tbm fatiamento, porem com definicoes diferentes

[[20. 30.]]
[20. 30. 40. 50.]


Compartilhamento de memoria do array

In [16]:
x = np.array([1, 2, 3])
y = x[:2] # gerara na memoria, o mesmo valor para x e y, ficando uma shadow copy
y[0] = -100 #a mudanca sera efetuada para ambas as variaveis
z = y.copy() # com esse metodo, as variaveis ficaram independentes
z = 2
print(x, y, z)


[-100    2    3] [-100    2] 2
