In [8]:
import numpy as np

x = np.array([[1, 3, 7],
             [4, 11, 21],
             [42, 8, 9]])
print(x)

[[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [ ]:
# reshape
print(x.reshape(9, 1)) # redimensiona o array de acordo com o definido em numero de L e C
print(x.reshape(1 ,9))
# o valor condicionado tem que ser coerente com o array

In [ ]:
# transposicao de matriz
print(x.T) # transforma linhas em colunas e vice-versa

In [ ]:
# metodo .sum e .mean
print(x)
print(np.sum(x)) # retorna a soma de todos os elementos
print(np.sum(x, axis=0)) # axis = 0 significa linha, logo vai somar o elementos de cada linha
print(np.sum(x, axis=1)) 

print(np.mean(x)) # retorna a media de todos os elementos
print(np.mean(x, axis=0)) 
print(np.mean(x, axis=1)) 

np.median # retorna a mediana

In [ ]:
# np.where retornara os indices de uma determinada condicao

cond = x % 2 == 0
print(cond)
i, j = np.where(cond)
print(i)
print(j) # vai retornar os indices em linhas e colunas onde a condicao for verdadeira


